language: ruby
rvm:
  - "1.9.3"
before_script: bundle exec rake db:migrate
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "irc.case.edu#project-october"
